whywaita/myshoes

- pkg/starter/scripts.go
Newest GitHub Actions runner can't run in some environments (e.g. GitHub Enterprise Server).
> pinned version of GitHub Actions runner

- pkg/starter/scripts.go
e.g. [actions/setup-go](https://github.com/actions/setup-go) 
setup-go need GOPATH, GOPATH default value is `$HOME/go`.
> some setup actions need HOME environment value

- pkg/starter/scripts.go
`user-data` in cloud-init can not receive the long scripts in some environments.
So compress by gzip and base64, and decompress in a worker.
> compress setup script by gzip and base64

- .github/workflows/release.yaml
https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358
> GitHub Package need credential, also push to Docker Hub

- pkg/starter/scripts.go
Another worker dequeues new jobs if already registered environments.
add label `myshoes` to self-hosted runner after applying this patch.
> add label for runner

- pkg/web/webhook.go
fix: #81 
return err if already deleted target in a repository
> Check err is nil

- pkg/gh/github.go
- pkg/starter/starter.go
- pkg/web/http.go
> Check to register in GitHub before deleting job

- docs/01_01_for_admin_setup.md
- go.mod
- go.sum
- internal/config/config.go
- internal/config/init.go
- pkg/gh/github.go
- pkg/metric/scrape_memory.go
- pkg/runner/runner_delete.go
- pkg/runner/runner_delete_ephemeral.go
- pkg/runner/runner_delete_once.go
- pkg/starter/starter.go
fix: #36 
- Add config value: `MAX_CONCURRENCY_DELETING`
- Bulk get in `runner`
- Reduce calling REST API
> Implement fast-deleting

- pkg/gh/token_registration.go
This change fixes this error.
```
./config.sh --unattended --url https://github.com/xxx/xxx --token *** --name myshoes-xxx --labels myshoes --ephemeral
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        | …
```
> Org token and Repo token has a same installation ID

- pkg/datastore/mysql/target_test.go
- pkg/web/target.go
- pkg/web/target_test.go
Prevent an error even if the user specifies ghe_domain when registering a target
- user command example
```
$ curl -XPOST https://${myshoes_shot} -d '{"scope": "xxxx", "ghe_domain": "", "resource_type": "large",  "runner_user": "runner", "runner_version": "v2.302.1"}'
{"error":"json decode error"}
```
- myshoes error log
```
myshoes 2023/03/08 05:24:22 failed to decode request body: json: cannot unmarshal string into Go struct field TargetCreateParam.ghe_domain of type sql.NullString
```
> add GHEDomain in TargetCreateParam

- internal/config/init.go
The plugin path displayed empty because the Config variable was referenced before it was assigned to the Config variable.
Therefore, the issue has been corrected.
> Fix plugin path variable in log output

- pkg/starter/scripts.go
The following line was interpreted by bash causing the `Runner listener exited with error code ` to be executed as a command.
https://github.com/whywaita/myshoes/blob/309d5260eb41cf6a234a0c2b1a110a94bb937406/pkg/starter/scripts/RunnerService.js#L44
> Do not execute backquoted as shell command in RunnerService.js

- pkg/starter/scripts.go
Move extracted runner to `/tmp/runner` from `/usr/local/etc/runner-${RUNNER_VERSION}` if exists.
> Use extracted runner cache

- cmd/server/cmd.go
- internal/testutils/testutils.go
- pkg/datastore/mysql/job.go
- pkg/datastore/mysql/mysql.go
- pkg/starter/starter.go
After enqueuing a job, notify that a new job is available to the starter immediately by using channel.
This will reduce the time until the runner is started by up to 10 seconds.
> Notify to starter when new job enqueued

- docs/01_01_for_admin_setup.md
The environment variable `GITHUB_APP_SECRET` must be equal to the GitHub App's webhook secret, but that wasn't obvious to me, so I added a description to make it clear.
> Add description for GITHUB_APP_SECRET environment variable in 01_01_for_admin_setup.md

- docs/01_02_for_admin_tips.md
- pkg/starter/scripts.go
https://github.blog/changelog/2022-04-04-github-actions-job-management-hooks-for-self-hosted-runners/
- `ACTIONS_RUNNER_HOOK_JOB_STARTED`: `/myshoes-actions-runner-hook-job-started.sh`
- `ACTIONS_RUNNER_HOOK_JOB_COMPLETED`: `/myshoes-actions-runner-hook-job-completed.sh`
> Support job management hooks

- pkg/shoes/shoes.go
- pkg/starter/starter.go
fixes: #183 
Change DeleteJobs to run when invalid labels are enqueued and InvalidArgument is returned by AddInstance().
For example, when AddInstance() is executed, jobs with InvalidArgument are never deleted.
Therefore, it will remain in the queue and may hit the rate limit of GitHubAPI.
> Add error handling for invalid labels to AddInstance()

- docs/01_01_for_admin_setup.md
I found this today on my own instance of myshoes. 
`2024/05/02 19:40:00 receive WorkflowJobEvent, but set check_run. So ignore`
I checked the code ...
https://github.com/whywaita/myshoes/blob/603c51b07c194f6d0e98218b65a5568ce8e3fc2c/pkg/config/init.go#L63
and indeed the default is not `workflow_job`
> Default is actually check_run

- .github/workflows/build-docker-sha.yaml
- docs/01_01_for_admin_setup.md
- pkg/config/config.go
- pkg/config/init.go
- pkg/docker/ratelimit.go
- pkg/metric/scrape_memory.go
provide docker hub ratelimit as a metric
https://docs.docker.com/docker-hub/download-rate-limit/#how-can-i-check-my-current-rate
> add docker hub ratelimit metric

- docs/01_01_for_admin_setup.md
- pkg/config/config.go
- pkg/config/init.go
For more flexibility, "mysqlurl" is constructed from "MYSQL_HOST", "MYSQL_PORT", "MYSQL_USER", "MYSQL_PASSWORD", and "MYSQL_DATABASE" environment variables only if all of them exist.
> Generate a mysqlURL from host, port, user, password, database

- pkg/gh/run.go
- pkg/metric/scrape_github.go
- pkg/starter/starter.go
`ds.GetTargetByScope` does not support searching an organization target from the repository name.
This pull-request change to use `datastore.SearchRepo`.
> Fix to search repository in rescue

- pkg/web/webhook.go
With [myshoes#171](https://github.com/whywaita/myshoes/pull/171), myshoes was made compatible with dependabot on GitHub Enterprise Server (GHES).
However, since then, the specification for `runs-on` has changed. Specifically, the `self-hosted` label has been removed, and only `dependabot` is now specified under `runs-on`.
This update modifies myshoes to accommodate this change, ensuring it continues to function correctly.
> Accept dependabot in GHES

- pkg/starter/scripts.go
Remove node16 runtime in actions/runner by https://github.com/actions/runner/pull/3503
ref: https://github.com/actions/runner/releases/tag/v2.321.0
node22 is not published yet.
> Support node20

- pkg/gh/installation.go
- pkg/gh/jwt.go
- pkg/metric/scrape_datastore.go
- pkg/metric/scrape_github.go
This pull request includes significant changes to the GitHub integration and Prometheus metrics collection. The most important changes are the addition of new functions for listing GitHub installations and enhancements to the Prometheus metrics for datastore and GitHub installations.
* Added a new function `listInstallations` in `pkg/gh/installation.go` to list GitHub installations with caching to improve performance.
* Removed the redundant `listInstallations` function from `pkg/gh/jwt.go` as it was moved to `pkg/gh/installation.go`.
* Added new Prometheus metrics descriptors for datastore targets and token expiration times in `pkg/metric/scrape_datastore.go`.
* Updated the `scrapeTargets` function in `pkg/metric/scrape_datastore.go` to include the new metrics for datastore targets and …
> Add a metrics of GitHub Apps installation

- pkg/starter/scripts.go
We found *not* loaded a custom PATH that generated from a script of `actions/runner-images` in myshoes runner.
But I found setting environment values in `/opt/runner/provisioner/provisioner` in GitHub-hosted runner.
```
root         715  0.2  0.8 274207752 146996 ?    Ssl  17:29   0:02 /opt/runner/provisioner/provisioner --agentdirectory /home/runner/runners --settings /opt/runner/provisioner/.settings
root        1715  0.1  0.1 1242976 22164 ?       Sl   17:37   0:01  \_ /opt/runner/provisioner/etc/provjobd
runner      1727  0.2  0.7 274209476 130888 ?    Sl   17:37   0:02  \_ /home/runner/runners/2.321.0/bin/Runner.Listener run
runner      1743  0.5  1.1 274293808 183244 ?    Sl   17:37   0:05      \_ /home/runner/runners/2.321.0/bin/Runner.Worker spawnclient 155 158
```
pid 1727 ( …
> Load custom path from /etc/environment in setup script

- pkg/gh/installation.go
- pkg/starter/starter.go
fixes: #230 
This pull request introduces enhancements to GitHub installation handling, including a new function to retrieve installation data from the cache and updates to the workflow rescue logic to utilize this cached data. These changes improve efficiency and fallback mechanisms when dealing with GitHub installations.
* **Added `GetInstallationByID` function**: Introduced a new function in `pkg/gh/installation.go` to retrieve installation data from the cache using an installation ID. This function iterates through cached installations and provides fallback error handling if the installation is not found.
* **Utilized cached installation data in `enqueueRescueRun`**: Modified the workflow rescue logic in `pkg/starter/starter.go` to retrieve full installation data from the cache using …
> Set installation object in rescue

- pkg/starter/starter.go
fixes: #232 
ErrInvalidLabel is not an error of booting the runner.  So the myshoes needn't tell the error to the user.
This pull request introduces a small but significant change to the `ProcessJob` function in `pkg/starter/starter.go`. The change ensures that the function exits early with a `nil` return value after successfully incrementing the delete job metrics.
* [`pkg/starter/starter.go`](diffhunk://#diff-3a0c64b483dd2fed243139d0725e8be15f12e642cd167cd9ce85923e63d138c5R226): Added an early `return nil` statement after `incrementDeleteJobMap(job)` to prevent further execution when the delete metrics are successfully incremented.
> Don't store error when ErrInvalidLabel

- pkg/datastore/github.go
- pkg/starter/starter.go
We fixed a bug with the rescue bomb in the pending run.
This pull request refines the logic in the function `GetPendingWorkflowRunByRecentRepositories` within the `pkg/datastore/github.go` file. The update improves the handling of pending workflow runs by ensuring that jobs already queued are correctly identified and excluded from the result.
* Added a `found` flag to track whether a pending workflow run matches a queued job. This ensures that the loop breaks immediately upon finding a match, optimizing performance.
* Updated the logic to append only unmatched pending workflow runs to the `result` slice, enhancing the accuracy of the filtering process.
> Fix a flag for found job in rescue

- pkg/gh/label.go
- pkg/starter/scripts.go
- pkg/starter/starter.go
- pkg/web/webhook.go
fixes: https://github.com/whywaita/myshoes/issues/228
- We check labels in the rescue job.
- The myshoes don't rescue a job that was not generated by myshoes.
- We always add the `dependabot` label.
- This change supports https://docs.github.com/en/code-security/dependabot/maintain-dependencies/managing-dependabot-on-self-hosted-runners
This pull request refactors label-checking logic to improve code reusability and maintainability. The key changes include introducing a new utility function `IsRequestedMyshoesLabel` in the `pkg/gh/label.go` file and replacing duplicate label-checking logic with calls to this function across the codebase.
* Added the `IsRequestedMyshoesLabel` function in `pkg/gh/label.go` to encapsulate the logic for checking if a job has appropriate labels (`myshoes`, …
> Add check of invalid label in rescue
