whywaita/myshoes

- pkg/runner/runner.go
fix: #20 
GitHub will delete offline runners that offline for 30days, so check count of runners.
> switch status to error if target has not runner

- pkg/datastore/interface.go
- pkg/datastore/memory/memory.go
- pkg/datastore/mysql/runner.go
- pkg/datastore/mysql/runner_test.go
- pkg/datastore/mysql/schema.sql
- pkg/datastore/mysql/target.go
- pkg/datastore/mysql/target_test.go
- pkg/runner/runner.go
- pkg/starter/starter.go
fix: #24 
set `completed` or `reach_hard_limit` to runner.status when delete runner.
> add column "status" to runner

- pkg/datastore/interface.go
- pkg/datastore/mysql/job_test.go
- pkg/datastore/mysql/schema.sql
- pkg/datastore/mysql/target.go
- pkg/datastore/mysql/target_test.go
- pkg/starter/scripts.go
- pkg/starter/starter.go
- pkg/web/target.go
- pkg/web/webhook.go
> fix #11, #31

- docs/myshoes.service
> add myshoes.service

- pkg/datastore/mysql/target.go
- pkg/datastore/mysql/target_test.go
- pkg/web/target.go
- pkg/web/target_test.go
> can not delete target if runner is exist. so switch logical delete

- internal/config/init.go
> need to close opened file

- pkg/datastore/interface.go
- pkg/gh/github.go
- pkg/runner/runner.go
- pkg/web/target.go
- pkg/web/target_create.go
- pkg/web/target_test.go
check current status in datastore
> validate input from REST API

- pkg/datastore/interface.go
- pkg/runner/runner.go
- pkg/web/target.go
> ListTarget do not return target that can not receive job

- .github/workflows/release.yaml
> add semver and sha tag for docker image

- pkg/web/webhook.go
> searchRepo check target that can receive job

- pkg/datastore/interface.go
- pkg/datastore/mysql/schema.sql
- pkg/datastore/mysql/target_test.go
- pkg/runner/runner.go
- pkg/web/target_create.go
- pkg/web/target_test.go
check permission before creating target in https://github.com/whywaita/myshoes/pull/52 .
So this change removes initialize state.
> Remove initialize state of target

- cmd/server/cmd.go
- pkg/runner/runner.go
- pkg/starter/starter.go
- pkg/web/http.go
> Check all targets even if there is an error

- pkg/gh/jwt.go
- pkg/web/target.go
- pkg/web/target_create.go
- pkg/web/target_test.go
> Remove sql.NullString from HTTP response

- cmd/server/cmd.go
- pkg/datastore/interface.go
- pkg/datastore/memory/memory.go
- pkg/datastore/mysql/lock.go
> Implement datastore lock

- pkg/starter/starter.go
60 seconds is short in a some environments
> Expand timeout of creating runner

- pkg/gh/github.go
> Fix calling GitHub API code

- pkg/gh/github.go
- pkg/gh/jwt.go
- pkg/gh/jwt_test.go
- pkg/runner/runner.go
- pkg/web/target.go
- pkg/web/target_create.go
- pkg/web/target_test.go
> Delete callAPIPrivateKey, using go-github

- pkg/runner/runner.go
> Token updator need to run always, but a same loop block other logic

- docs/01_01_for_admin_setup.md
- internal/config/config.go
- internal/config/init.go
- pkg/metric/collector.go
- pkg/metric/scrape_memory.go
- pkg/starter/starter.go
fix: #106 
- Switch algorithm job queuing model to dispatcher-worker from sequential
- Add metrics
- `myshoes_memory_starter_max_running`
- `myshoes_memory_starter_queue_running`
- `myshoes_memory_starter_queue_waiting`
> Switch to dispatcher-worker method

- pkg/datastore/interface.go
- pkg/datastore/memory/memory.go
- pkg/datastore/mysql/runner.go
- pkg/runner/runner_delete.go
- pkg/runner/runner_delete_ephemeral.go
- pkg/runner/runner_delete_once.go
- pkg/web/target.go
- pkg/web/target_create.go
> Use same delete logic in mode once as a mode epehemeral

- go.mod
- go.sum
- pkg/gh/github.go
> Use conditional GET by httpcache

- pkg/runner/runner_delete.go
> will delete from runners_runing if not found from shoes

- pkg/gh/github.go
- pkg/gh/jwt.go
- pkg/gh/jwt_test.go
For `rate_limit_exceeded`
Ref:
- https://docs.github.com/en/rest/overview/resources-in-the-rest-api#pagination
- https://docs.github.com/en/rest/reference/actions#list-self-hosted-runners-for-an-organization
> per_page | integer | query | Results per page (max 100)Default: 30
> Set per_page is max value

- pkg/datastore/mysql/job.go
- pkg/datastore/mysql/job_test.go
- pkg/metric/scrape_datastore.go
> Add job_duration_oldest_seconds

- go.mod
- go.sum
- pkg/datastore/mysql/job.go
- pkg/datastore/mysql/job_test.go
- pkg/gh/github.go
- pkg/gh/runner.go
- pkg/metric/scrape_datastore.go
- pkg/web/target.go
- pkg/web/target_create.go
- pkg/web/target_test.go
> Add validate in modify target

- pkg/runner/runner_delete.go
- pkg/starter/starter.go
> Set status is active if target hasn't runner for queue in ephemeral mode

- pkg/runner/runner.go
Co-authored-by: camonster <camonster@users.noreply.github.com>
> Not deleting before limit of GitHub Actions

- pkg/datastore/interface.go
- pkg/datastore/mysql/job_test.go
- pkg/datastore/mysql/target.go
- pkg/web/target_create.go
・Our components require a ghe_domain item, so We need to embed the value when creating the target
> Restore ghe_domain in targets

- pkg/web/target_create.go
For github.com,
you need to put NULL in ghe_domain instead of "" string.
> fix ghe_domain for https://github.com

- pkg/starter/scripts.go
> dependabot for GHES needs self-hosted runner

- docs/01_01_for_admin_setup.md
- docs/02_01_for_user_setup.md
Fix documentation due to changes in #164.
> Fix documents about runner_user

- Dockerfile
- go.mod
- go.sum
- pkg/metric/scrape_memory.go
- pkg/runner/runner_delete.go
- pkg/starter/starter.go
> Use atomic for global variable ConcurrencyDeleting

- pkg/metric/scrape_memory.go
- pkg/starter/starter.go
> add rescued jobs metrics

- pkg/starter/starter.go
Without ticker, CPU utilization is high.
> use ticker in reRunWorkflow

- go.mod
- go.sum
- pkg/starter/starter.go
- fix re-queue bad-label jobs
- add continue label
> fix re-queue bad label jobs

- pkg/gh/runner.go
- pkg/metric/scrape_datastore.go
- pkg/starter/metric.go
- pkg/starter/starter.go
Add `myshoes_datastore_deleted_jobs`
> New metric for notify invalid label job

- .github/workflows/test.yaml
- Dockerfile
- api/myshoes/client.go
- go.mod
- pkg/datastore/interface.go
- pkg/datastore/mysql/target_test.go
- pkg/docker/ratelimit.go
- pkg/runner/runner_delete.go
- Upgrade to Go 1.23
- Switch to stackcheck for lint (golint is deprecated)
> Improve to modernization

- pkg/config/init.go
> Check plugin binary response valid binary

- pkg/datastore/interface.go
- pkg/metric/scrape_github.go
I found it
```
2024/12/16 07:10:35 failed to get target by scope (xxx/xxx): failed to get target from organization: %!w(<nil>)
```
> Refactor an error message
